kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openebs-dbench-pv-claim
spec:
  storageClassName: openebs-jiva-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench
spec:
  template:
    spec:
      containers:
        - name: dbench
          image: chph/dbench:v1.0.0
          imagePullPolicy: Always
          env:
            - name: DBENCH_MOUNTPOINT
              value: /data
            # - name: DBENCH_QUICK
            #   value: "yes"
            # - name: FIO_SIZE
            #   value: 1G
            # - name: FIO_OFFSET_INCREMENT
            #   value: 256M
            - name: FIO_DIRECT
              value: "1"
          volumeMounts:
            - name: dbench-pv
              mountPath: /data
      restartPolicy: Never
      volumes:
        - name: dbench-pv
          persistentVolumeClaim:
            claimName: openebs-dbench-pv-claim
  backoffLimit: 4
